### ISSUE TITLE
Discovery can avoid multicast ?

### ISSUE THREAD

**Issue by chemelli74** [StyraHem/pyShelly#12]
Hi,

many of us have issues on their routers with Multicast on 224.0.1.187.

Can the discovery be switched to another protocol ? 
Or is the Multicast mandatory for the subseguent usage of the tool ?

Thank you in advance for your help and effort.
Cheers,

Simone

**Comment by hakana** [comment]
I'm working on that ;) 50% ready. In release 0.1.2 it can use rest API to get status. I need to fix discovery to work with mdns and manually add by ip address. A network scan discover also.

**Comment by Misiu** [comment]
I think that defining devices by IP is enough.
Most of us (if not all??) assign static IP to Shelly devices on the router. Autodiscovery would be super useful if You have a lot of devices in your house and you are just starting with HA, but I think that all of us won't mind adding the devices manually.
From the other side, discovery will be super useful when adding SHellyForHASS to HA, this way when adding component the devices could be added at the start.

**Comment by chemelli74** [comment]
> I'm working on that ;) 50% ready. In release 0.1.2 it can use rest API to get status. I need to fix discovery to work with mdns and manually add by ip address. A network scan discover also.

Thank you for your great work!
Now I get my Shelly discovered using latest master version of ShellyForHASS (mix of 0.1.2/0.1.3):

![image](https://user-images.githubusercontent.com/57354320/69884366-61b96f80-12d8-11ea-8a18-9e99bc90f458.png)

Just a small side note: I had to manually download and copy the updated versions of each "py" files as custom_updater.json still report "0.1.0" as latest version.

Cheers,

Simone
