### ISSUE TITLE
mDns discovery, problem between VLANS

### ISSUE THREAD

**Issue by arraylabs** [StyraHem/pyShelly#13]
Continually get the following message in logs:

"WARNING (Poll) [pyShelly] Error, 301 Moved Permanently"
"/usr/local/lib/python3.7/site-packages/pyShelly/utils.py (WARNING)"

Everything seems to work fine but the message persists. I have reinstalled home assistant a few times and the message always comes back. I will get thousands of these messages. 

I have the latest version of HASS, and pyshelly via HACS. Running HASS via docker not hassio. Not sure if it matters but I have the Shellies on a VLAN and use the proxy setup to send messages across the VLAN into the LAN. Been getting that message for weeks now.

**Comment by hakana** [comment]
Does HA have http access to your Shellies?

**Comment by arraylabs** [comment]
While inside the HA docker shell I do get a 200 response via curl to one of the shelly devices on port 80.

**Comment by arraylabs** [comment]
Additional information, appears that setting mdns: false gets rid of this message. Will keep an eye out to see if that statement remains true. If it does, is it an issue of the mdns messages traversing the VLAN to LAN? I do have a repeater setup in OPNsense.

**Comment by elahd** [comment]
I'm running into the same issue. I have a pretty convoluted setup. Shelley is on VLAN 400. HA is on VLAN 200. My router's mDNS reflector is enabled. Using tcpdump from within VLAN 200, I see the below broadcast from the shelley:

`17:03:03.239487 IP 192.168.2.1.5353 > 224.0.0.251.5353: 0* [0q] 6/0/0 PTR _http._tcp., PTR shellyrgbw2-XXXXXX._http._tcp.local., (Cache flush) SRV shellyrgbw2-XXXXXX.local.:80 0 0, (Cache flush) TXT "id=shellyrgbw2-XXXXXX" "fw_id=20191216-090536/v1.5.7@c30657ba" "arch=esp8266", (Cache flush) A 192.168.4.4, (Cache flush) NSEC (433)`

It looks like the mDNS message broadcasts from the router's IP on VLAN 200 (192.168.2.1). That same message contains the shelley IP (192.168.4.4) in an A record.

For contrast, my Apple TV is on the 200 VLAN. tcpdump from within VLAN 200 shows the following message:

`17:03:07.798694 IP 192.168.2.106.5353 > 224.0.0.251.5353: 0*- [0q] 3/0/1 PTR e0:c7:67:82:e5:68@fe80::e2c7:67ff:fe82:e568._apple-mobdev2._tcp.local., PTR e0:c7:67:82:e5:68@fe80::e2c7:67ff:fe82:e568._apple-mobdev2._tcp.local., PTR e0:c7:67:82:e5:68@fe80::e2c7:67ff:fe82:e568._apple-mobdev2._tcp.local. (175)`

The message is from the Apple TV's IP address, not the router's. There's no A record.

It looks like pyShelly is reading the "from" IP address exclusively.

**Comment by hakana** [comment]
Ok, that explains this!
Our mDns implementation only looks on the **from** address. I will check this later and try to find a solution.
@elahd  Can run the CoAP proxy.py on your VLAN 400 ?

**Comment by elahd** [comment]
Discovery works when the proxy is running in VLAN 400:

![image](https://user-images.githubusercontent.com/466460/75599010-b6eb5580-5a6e-11ea-9e88-ebfa3f9d0582.png)

**Comment by hakana** [comment]
I think this issue is solved when we change the mDns code.
