### ISSUE TITLE
RGBW2-Switch state not updated

### ISSUE THREAD

**Issue by hk-ret** [StyraHem/pyShelly#16]
The Switch class fails to update state changes for RGBW2 devices. These deliver only a single `input` key in the state collection instead of an `inputs` list containing `input` keys.

**Comment by hakana** [comment]
I don't understand, can you please explain what you want to do?

**Comment by hk-ret** [comment]
The method `update_status_information` of the class `Switch` is extracting the switch-state from the parameter `status`. It expects a list of inputs and uses `self._channel` to get the desired input. However the Shelly RGBW2 devices don't return a list of inputs but a single `{'input': value}` entry in `status`.

I suggest the method `update_status_information` should extract the new state like this:
```
        inputs = status.get(STATUS_RESPONSE_INPUTS)
        if inputs:
            value = inputs[self._channel]
            new_state = value.get(STATUS_RESPONSE_INPUTS_INPUT, None)
        else:
            new_state = status.get(STATUS_RESPONSE_INPUTS_INPUT, None)
```

BTW: This is only an issue for RGBW2, while Shelly-1's having also only 1 input return a list with 1 element.

**Comment by hakana** [comment]
Is this still an issue?
