### ISSUE TITLE
[pyShelly] Error adding device

### ISSUE THREAD

**Issue by Gepstra** [StyraHem/pyShelly#17]
Hi everyone,

I'm getting these errors since yesterday. Is pyShelly not installed correctly? 

Running in Docker on Synology NAS.

```
2020-04-12 18:02:40 WARNING (Poll) [pyShelly] Error, 404 Not Found                                                                                                                                       
2020-04-12 18:02:40 INFO (Poll) [pyShelly] Error adding device, 172.30.32.1
```

I've set it up in configuration.yaml. Both Shelly's are already visible in Integrations and are working. 

```
shelly:
 username: admin
 password: !secret shellypassword
```
Also this: 
![firefox_ZmNifsGt5L](https://user-images.githubusercontent.com/32432776/79074047-69f3d380-7cea-11ea-8d67-fef2df19ba78.png)

Any ideas?

**Comment by hakana** [comment]
Try add mdns: false to you config.yaml under Shelly

**Comment by Gepstra** [comment]
Thanks, seems to have fixed it. 

But there must still be something wrong with my install because I didn't get the errors before. We'll see.
