### ISSUE TITLE
Use build-in MQTT broker

### ISSUE THREAD

**Issue by fjufju** [StyraHem/pyShelly#18]
Hi there,
consider using build-in broker, like Mosquitto.
It is easy to setup and many times users already use it.
Not sure if having two MQTT brokers will be damage, but why not use the one already on home assistant. Performance will be better I think.

Thank you for awesome work!!! 🎉

**Comment by hakana** [comment]
The reason I added the build-in MQTT server is that it can be used without any configuration. I look on integrating with the built-in MQTT server also.

**Comment by fjufju** [comment]
@hakana thank you for updates :)

**Comment by srgvg** [comment]
Was wondering that myself, too. 
Please note, IIRC the lightweight built-in mqtt server in HA is deprecated.
The MQTT integration from HA (https://www.home-assistant.io/integrations/mqtt/) is the recommended way.

(Found out about this update only recently. Any update on this?)

**Comment by hakana** [comment]
Added in latest release
