### ISSUE TITLE
ERROR (Poll status) [pyShelly] Timeout connecting to http://192.168.xx.xx/status

### ISSUE THREAD

**Issue by Rossez** [StyraHem/pyShelly#44]
Hello,

in my HA log following errors started to appear about 3 weeks ago (randomly about 50-100 error logs per day):

`ERROR (Poll status) [pyShelly] Timeout connecting to http://192.168.xx.xx/status`

The URL is accessible fine from client on local netowork. The error appears for different shelly devices (different IPs). My configuration:

- pyShelly 0.2.0 (latest)
- Supervised Home Assistant 0.117.2 (latest) running in docker on Synology NAS DS918+
- docker container is configured to use host network

The problem is probably network related. Is there a way I can test the URL directly from docker environment? Or any other suggestions? Thank you.

**Comment by Rossez** [comment]
Will post the issue under ShellyForHASS

**Comment by martin3000** [comment]
the timeout is hardcoded to 5s in utils.py
