### ISSUE TITLE
Devices not found

### ISSUE THREAD

**Issue by lukakiro** [StyraHem/pyShelly#5]
I'm using pyShelly (installed via `pip install pyShelly`) version 0.0.30 in a python 3.7.3 virtual environment on a raspberryPi 3B+ connected via ethernet.
In the same network there are 2 shelly devices: a shelly1 and a shelly2, both with CoAP option enabled.
When I run the script provided in the readme file nothing is printed.
What's the problem? I'm missing something?

```python
import pyShelly from pyShelly

def device_added(dev):
  print (dev.devType)

shelly = pyShelly()
shelly.cb_device_added.append(device_added)
shelly.open()
shelly.discover()
```

**Comment by hakana** [comment]
Hi, test this:

```python
#Test

import time
from pyShelly import pyShelly

def device_added(dev, code):
  print (dev.type)

shelly = pyShelly()
shelly.cb_device_added.append(device_added)
shelly.open()
shelly.discover()

while True:
    time.sleep(5)
```

**Comment by lukakiro** [comment]
Hi, I tested your new script, but nothing is printed.

I checked with tcpdump which CoAP packets are transmitted and I can see one packet sent to 224.0.1.187

![image](https://user-images.githubusercontent.com/9718198/58897370-6e2d8880-86f8-11e9-937f-ab1cb12c8ad8.png)

Instead with a pc connected over Wifi, using Wireshark I can see CoAP packets from both shelly to 224.0.1.187

![image](https://user-images.githubusercontent.com/9718198/58897481-b187f700-86f8-11e9-8241-876b24d1bab5.png)

**Comment by hakana** [comment]
Ok, this is not a probmem with the library. It probably because your firewall not allow multicasts or an option in linux that disable it.
