### ISSUE TITLE
Is there a documentation?

### ISSUE THREAD

**Issue by padmalcom** [StyraHem/pyShelly#63]
Hi, thanks for your effort implementing this library. I came here to show values measured by my shelly h&t but I do not really know how to set it up. Is there anywhere any kind of documentation or an example?

**Comment by markus7017** [comment]
the binding has a README or what are you looking fot?

**Comment by hakana** [comment]
https://github.com/StyraHem/ShellyForHASS

**Comment by HoWilgh** [comment]
A short pure-Python example for switching e.g. a Shelly1Plus On and off would be very helpfull. 
The link to the repo for using this in Home-Assistant is not what one is looking for when searching for pyShelly =) (coming from python.org).

**Comment by HoWilgh** [comment]
> Hi, thanks for your effort implementing this library. I came here to show values measured by my shelly h&t but I do not really know how to set it up. Is there anywhere any kind of documentation or an example?

This is a kind of Frankenstein code for a shelly with a fixed IP but it works for me and hopefully helps you and others ....
```
from pyShelly import pyShelly

def device_added(dev,code):
  print (dev," ",code)

shelly = pyShelly()
print("version:",shelly.version())

shelly.cb_device_added.append(device_added)
shelly.start()
#shelly.discover()

#while True:
#    pass 

shelly.add_device_by_ip("192.168.101.46", 'IP-addr')  # this takes some time 

import time
time.sleep(15)

shelly.devices # look for Relays
n = 0  # index in devices
shelly.devices[n].device_type

if shelly.devices[n].device_type == 'RELAY':
  if not shelly.devices[n].turn_off():
    shelly.devices[n].turn_off()
    time.sleep(3)
  shelly.devices[n].turn_on()
  time.sleep(3)
  shelly.devices[n].turn_off()
```

If you just need to do simple tasks maybe you want to use the standard library requests:
```
import requests
r =requests.get('http://192.168.33.1/rpc/Sys.GetStatus')
print(r.text)

r =requests.get('http://192.168.33.1/relay/0?')
r_dictionary= r.json()
print(r_dictionary['ison'])

import time
if not r_dictionary['ison']:
  print('Relay is off and will be turned on.')
  r =requests.get('http://192.168.33.1/relay/0?turn=on')
  time.sleep(3)
print('Relay will be turned off.')
r =requests.get('http://192.168.33.1/relay/0?turn=off')
```

**Comment by padmalcom** [comment]
Thank you, that looks good to me. I'll try it on a free weekend.

**Comment by Uniphase38** [comment]
Hi guys, is there a sort of discover fonction to fetch, IPs, names?
