### ISSUE TITLE
Issue in pyshelly is flooding the logfile

### ISSUE THREAD

**Issue by galex80** [StyraHem/pyShelly#64]
I'm not sure, where the problem is coming from, but i recognized this problem in my logs since the last firmware update of the shelly devices.

I'm running latest Home Assistant Version 2021.7.4 with latest Shelly4HASS Version 0.2.3.beta.2

Any help are much appreciate!

Logger: pyShelly
Source: /usr/local/lib/python3.9/site-packages/pyShelly/utils.py:39
First occurred: 10:27:55 AM (96223 occurrences)
Last logged: 10:34:21 AM

Error update loop, '>' not supported between instances of 'datetime.timedelta' and 'int', Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/pyShelly/__init__.py", line 335, in _update_loop block.loop() File "/usr/local/lib/python3.9/site-packages/pyShelly/block.py", line 141, in loop if self._need_setup_delayed_devices and self._check_delay_load.check(): File "/usr/local/lib/python3.9/site-packages/pyShelly/utils.py", line 29, in check now - self._last_time > self._interval: TypeError: '>' not supported between instances of 'datetime.timedelta' and 'int'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyShelly/__init__.py", line 335, in _update_loop
    block.loop()
  File "/usr/local/lib/python3.9/site-packages/pyShelly/block.py", line 141, in loop
    if self._need_setup_delayed_devices and self._check_delay_load.check():
  File "/usr/local/lib/python3.9/site-packages/pyShelly/utils.py", line 29, in check
    now - self._last_time > self._interval:
TypeError: '>' not supported between instances of 'datetime.timedelta' and 'int'

**Comment by shajek** [comment]
hello, i have same problem

```
Logger: pyShelly
Source: /usr/local/lib/python3.9/site-packages/pyShelly/utils.py:39
First occurred: 1:53:14 PM (105930 occurrences)
Last logged: 2:11:08 PM

Error update loop, '>' not supported between instances of 'datetime.timedelta' and 'int', Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/pyShelly/__init__.py", line 335, in _update_loop block.loop() File "/usr/local/lib/python3.9/site-packages/pyShelly/block.py", line 141, in loop if self._need_setup_delayed_devices and self._check_delay_load.check(): File "/usr/local/lib/python3.9/site-packages/pyShelly/utils.py", line 29, in check now - self._last_time > self._interval: TypeError: '>' not supported between instances of 'datetime.timedelta' and 'int'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyShelly/__init__.py", line 335, in _update_loop
    block.loop()
  File "/usr/local/lib/python3.9/site-packages/pyShelly/block.py", line 141, in loop
    if self._need_setup_delayed_devices and self._check_delay_load.check():
  File "/usr/local/lib/python3.9/site-packages/pyShelly/utils.py", line 29, in check
    now - self._last_time > self._interval:
TypeError: '>' not supported between instances of 'datetime.timedelta' and 'int'
```

what can i do with that ?
thank you

**Comment by hakana** [comment]
Fixed

**Comment by Keks1975** [comment]
Good afternoon!
in the logs HA log, the device is always in touch.
Logger: pyShelly
Source: /usr/local/lib/python3.10/site-packages/pyShelly/utils.py:94
First occurred: 09:53:07 (1 occurrences)
Last logged: 09:53:07

Timeout connecting to http://192.168.0.10/status [192.168.0.10]

**Comment by Keks1975** [comment]
it still gives an errorLogger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 10:13:25 (2 occurrences)
Last logged: 10:14:10

Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom integration author for shelly using this method at custom_components/shelly/__init__.py, line 356: await self.hass.helpers.entity_registry.async_get_registry()
Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom integration author for shelly using this method at custom_components/shelly/__init__.py, line 196: await self.hass.helpers.entity_registry.async_get_registry()

**Comment by Keks1975** [comment]
At the moment requested deletion did so
![image](https://user-images.githubusercontent.com/118057894/205021420-1ec6a482-f36d-4c09-99b5-aab1d5a35c39.png)


Logger: homeassistant
Source: custom_components/shelly/__init__.py:356
Integration: Shelly smart home ([documentation](https://github.com/StyraHem/ShellyForHASS/blob/master/README.md))
First occurred: 12:51:46 (1 occurrences)
Last logged: 12:51:46

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/shelly/__init__.py", line 356, in start_up
    await self.hass.helpers.entity_registry.async_get(hass)
NameError: name 'hass' is not defined

I get an error, what should I do?

**Comment by Ringo982** [comment]
Hi
i have the same prome here...
Log file is full of  TIMEOUT CONNECTING TO..... and TASK EXCEPTION WAS NEVER RETRIEVED (with async_get method problem)
Anyone can help to understand what to do to solve?
Thanks
