### ISSUE TITLE
Shelly 1 PRO

### ISSUE THREAD

**Issue by skydivingpt** [StyraHem/pyShelly#69]
Hi,

i have the new "Shelly 1 PRO",
in HomeAssistant 2022.5 (latest) i have this error :

```
**Log Details (WARNING)**

Logger: pyShelly
Source: /usr/local/lib/python3.9/site-packages/pyShelly/utils.py:76
First occurred: May 14, 2022, 11:56:19 PM (3 occurrences)
Last logged: May 14, 2022, 11:58:19 PM

Error, 404 Not Found http://< IP >/status
```

If i acess direct to "http://< IP >/" the device is there and all ok with it.

It seems that the 1 PRO does not have the standard "/status" page, so it gives the error .

Maybe its difrent on this model ?
https://shelly-api-docs.shelly.cloud/gen2/Components/SystemComponents/Sys#sysgetstatus-example 

Because if i go to :
http:// < IP >/rpc/Sys.GetStatus

i do get Info , like this :
![image](https://user-images.githubusercontent.com/655352/168451296-7f435a14-25db-4d18-8cd3-de460858ce56.png)

{"mac":"30C6Fxxxxxxxxx","restart_required":false,"time":"00:30","unixtime":1652571058,"uptime":844,"ram_size":239296,"ram_free":165568,"fs_size":524288,"fs_free":282624,"cfg_rev":51,"available_updates":{"beta":{"version":"0.10.2-beta1"}}}

Help pls

Tanks

**Comment by hakana** [comment]
Do you use latest beta version?

**Comment by skydivingpt** [comment]
Hi
yes, i have now , the beta 2,

the Pro 1, now shows OK :-D !

testing it now, with automations and so on,
so far, so good :-)

Many Tanks
will pay you a coffee :-)

**Comment by hakana** [comment]
Hi,

Do you use the latest beta of ShellyForHass?

If you do you can make an issue on Github and I will have a look at it.

Best regards
Håkan Åkerberg

Från: SkyPT ***@***.***>
Skickat: den 15 maj 2022 01:27
Till: StyraHem/pyShelly ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: [StyraHem/pyShelly] Shelly 1 PRO (Issue #69)


Hi,

i have the new "Shelly 1 PRO",
in HomeAssistant 2022.5 (latest) i have this error :

**Log Details (WARNING)**



Logger: pyShelly

Source: /usr/local/lib/python3.9/site-packages/pyShelly/utils.py:76

First occurred: May 14, 2022, 11:56:19 PM (3 occurrences)

Last logged: May 14, 2022, 11:58:19 PM



Error, 404 Not Found http://<IP>/status<http://%3cIP%3e/status>

If i acess direct to "http:///<http://>" the device is there and all ok with it.

It seems that the 1 PRO does not have the "/status" page, so it gives the error .

There not much info in Shelly also :-(
https://shelly-api-docs.shelly.cloud/gen2/Devices/ShellyPro1

Help pls

Tanks

**Comment by skydivingpt** [comment]
hi,

yes i have used the latest beta,
it worked out perfect,

this can be closed :-) 
let me know if any more info is needed.

Many Tanks & Keep up the great work  !
